swagger: '2.0'
info:
  version: '1.0'
  title: currencyapi.com
  description: 'CurrencyAPI.com Swagger '
  x-vcap-service-name: currencyapi.com
securityDefinitions:
  basicAuth:
    type: basic
security:
  - basicAuth: []
tags:
  - name: currencyapi.com
paths:
  /v3/status:
    get:
      operationId: getStatus
      summary: Retrieves the status
      description: Retrieves the status for the API user
      consumes:
        - text/plain
      produces:
        - application/json
      parameters:
        - name: apikey
          in: header
          required: true
          type: string
          description: API key
      responses:
        '200':
          description: The response when system finds an account with given name
          schema:
            $ref: '#/definitions/status'
  /v3/latest:
    get:
      operationId: getLatest
      summary: Retrieves the latest conversion rates
      description: Retrieves the latest conversion rates
      consumes:
        - text/plain
      produces:
        - application/json
      parameters:
        - name: apikey
          in: header
          required: true
          type: string
          description: API key
        - name: base_currency
          in: query
          required: true
          type: string
          description: Base Currency
        - name: currencies
          in: query
          required: true
          type: string
          description: Currencies to get
      responses:
        '200':
          description: The response when system finds an account with given name
          schema:
            $ref: '#/definitions/latest'
definitions:
  latest:
    required:
      - meta
      - data
    properties:
      meta:
        type: object
        description: metadata
        required:
          - last_updated_at
        properties:
          last_updated_at:
            type: string
            example: "2023-06-23T10:15:59Z"
      data:
        type: object
        example : {
          "CAD": {
            "code": "CAD",
            "value": 3.67306
          },
          "GPB": {
              "code": "GPB",
              "value": 91.80254
          },
          "USD": {
              "code": "USD",
              "value": 108.22904
          }
        }
        properties:
          CAD: 
            $ref: '#/definitions/currency_result'
          GBP: 
            $ref: '#/definitions/currency_result'
          USD: 
            $ref: '#/definitions/currency_result'
  status:
    required:
      - quotas
    properties:
      quotas:
        type: object
        description: quotas
        required:
          - month
        properties:
          month:
            type: object
            required:
              - total
              - used
              - remaining
            properties:
              total:
                type: number
              used:
                type: number
              remaining:
                type: number
  currency_result:
    properties:
      code:
        type: string
        example: "USD"
      value: 
        type: number
        example: 3.1234
